[package]
name = "actix-web-hello-world"
version = "0.0.1"
edition = "2018"
authors = ["Alex Fedoseev <alex.fedoseev@gmail.com>"]

[dependencies]
actix-web = "3.2.0"
ssr = { path = "../../ssr" }
log = "0.4.11"
env_logger = "0.8.1"
